name: Android APK Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Güncellendi

      - name: Extract ZIP
        run: |
          find . -name "*.zip" -exec unzip -o {} -d ./extracted_code \;

      - name: Set up JDK 17
        uses: actions/setup-java@v4 # Güncellendi
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: |
          find ./extracted_code -name "gradlew" -exec chmod +x {} +

      - name: Build with Gradle
        run: |
          GRADLEW_PATH=$(find ./extracted_code -name "gradlew" | head -n 1)
          if [ -z "$GRADLEW_PATH" ]; then echo "HATA: gradlew dosyası bulunamadı!"; exit 1; fi
          cd $(dirname $GRADLEW_PATH)
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Burası kritik: v4 yaptık
        with:
          name: HanGest-APK-Dosyam
          path: "**/build/outputs/apk/debug/*.apk"
